---
title: "Syllabus"
editor: visual
---

# Math 57, Fall 2022

Thinking with Data, Mondays 12:30-3:30pm\
California Rehabilitation Center, Norco, CA

#### Description:

Math 57 is a course designed to help you understand statistical reasoning. The emphasis will be on statistical thinking -- how to reason through the numbers you see in the media, in advertising, associated with medical claims, and from other sources. The applications of statistics to real-world problems go beyond using formulas on a dataset. Statisticians become involved in research problems at the initial stages of formulating the research hypotheses to be addressed and continue their involvement through the design and presentation of the results. This course exposes the student to the complete spectrum of activities in which a statistician is involved. Many topics from introductory statistics will be covered including conditional probability, sampling, hypothesis testing, and ethical reporting. Each topic will be contextualized within a context of interest where we see how data, analyses, and statistics generally can have large impacts on real lives. After taking Math 57, you will, hopefully, encounter numbers much differently.

#### Learning Objectives:

The goal of the course is for students to learn to critically evaluate numbers and related claims that are presented to them. To meet the goal, students will demonstrate their ability to achieve the following objectives: \* Given a report on a set of data, identify the population from which the data were collected and whether the sampling frame is the same as the population of interest. \* Identify whether a study is experimental or observational. List possible confounding variables and alternative causal mechanisms. \* Describe aspects of a graph which are informative and those which are misleading. \* Characterize different psychological aspects of probability estimation, and identify when those aspects are being used in reporting. \* Articulate different ethical aspects of the data collection, modeling, or reporting from a given data analysis.

#### Readings:

The assigned readings are to be done **prior to class meetings**, according to the attached schedule (see below). Both inside and outside students will be completing the same readings, so it will be expected that everyone will be "on the same page." If, for any reason, we/you do not meet on a particular day, please read the material for the day of class when we do meet (that is, skip the readings for the missed class) unless otherwise instructed.

-   **Important Note:** You will not be tested on the vocabulary, formulas, or examples. When you are reading, you should focus on the big ideas and not worry about the technical details or remembering every example. The textbook is there to give you a general background, and you should not try to memorize or understand every single detail.

#### Participation:

The format of our course will be highly interactive and discussion based. It is necessary for each student to attend and fully participate in every single class meeting. If you are absolutely unable to attend one of the sessions, let me know. Absences will change the dynamic and cohesion of the group. Actively participating in the discussion is also a key aspect of the course. In some classes we will be discussing topics which are controversial in nature. We will discuss ground rules and participation expectations when we meet, but know that you will be expected to actively listen to your colleagues and actively discuss the topics. In preparation for the meetings, you should **actively read** the material. It may help you to prepare the following. For particularly thorny topics, we will spend a good part of the class focused on student questions.

-   2 questions from things you didn't understand in the reading (from either the textbook or the course reader)
-   2 discussion questions for the class discussion (from the course reader, generally) which cannot be answered in one word (avoid yes/no or fact based questions).

At the beginning of every class, **each student** will share one aspect of the reading they found interesting. You should be prepared to bring one idea to class. We will spend the first bit of class focused on one or two of the items shared out. Our discussion will be much better if you bring something thorny to share -- either an idea which is hard to understand or controversial in nature. If you don't understand something, I promise that there are others in the room who don't understand. Let's talk about those concepts!!

#### Reflections:

After each class period, you will write a short reflection piece on the readings and class discussion (details below). You can choose to skip up to three reflection papers (you may not skip the Dear Data assignment) during the semester or to do more for extra credit. Five reflection papers are due over the course of the semester.

#### Grading:

Given the interactive nature of the course, one-third of the grade will be based on attendance and full participation. Full participation means paying attention, actively listening, contributing ideas from the readings, and joining the dialogue. One-third of the grade will be based on the reflection papers and draft paper. One-third of the grade will be based on the final project and written up final paper.

## Weekly Reflection Papers

The weekly papers are a particular kind of reflection paper. A paper will be due after each (most) class period(s); you may skip up to three reflection papers, if desired, or you may do more for extra credit. Each reflection paper should be typed (if possible), double-spaced, and three pages in length (longer if hand written). The papers will call for you to observe, feel, reflect, analyze, and integrate the information in the readings with the prior week's discussion. The format follows, including tips for how to write a strong paper.

Each paper should include three sections:

-   Section one: observations
-   Section two: analysis and integration
-   Section three: reactions

**Tip**: In your paper, be sure to clearly denote where each section begins.

### Section One: observations {.unnumbered}

Identify three things that you observed during our combined meeting. The observations can include anything that especially stood out for you, such as certain kinds of interactions between people, interesting issues or common themes that emerged (beyond the readings that we were discussing), insights about the dynamics of the group, etc. Explain was was important to you about each of the observations.

**Tip**: Be sure to include, and explain, *three* observations.

##### Example

During our discussion about sampling, I noticed that most of the situations described problematic sampling. For example, each of the examples created strong biases in the data collection. I would like to know more about how to take good and representative samples.

### Section Two: Analysis and Integration {.unnumbered}

In Section Two, you are to examine the statistical issues that were discussed in the class, reflecting on and analyzing the topics that were addressed, Integrate the readings for the week, including at least three quotes or references (with citations) from the readings. Section Two is the most difficult to write well. You are expected to present your own analysis based on the readings and discussions for each class meeting.

**Tip**: Prior to writing Section Two, you should reflect on the issues and themes that were discussed during the class meeting. What themes, points, or issues did you find interesting? Jot them down.

**Tip**: Since it is difficult to write about several issues well, select one of the issues or themes to write about.

**Tip**: Develop your own analysis of the issue or theme you select. What do *you* think about what you read and discussed during class?

**Tip**: Use the readings and examples from class discussion to support your analysis or to highlight the limitations of your analysis.

**Tip**: Do not forget to bring in either quotes or references from the readings that speak to the statistical content you are describing. \[The reference does not have to be a direct quote, see example below.\]

**Tip**: Ask yourself questions like: what do you find surprising? What do you agree/disagree with? What did you learn that was new to you?

##### Well written example

> In statistics, the gold standard for establishing a causal connection between two variables is through the use of a properly designed and executed experiment (Utts 1999, p. 189). Typically, a random experiment includes the use of random assignment which means that within a particular group the treatment is randomly assigned to each observational unit (Utts 1999, p. 6). If the experimenter assigns the treatment, the participants do not have the ability to choose which treatment they receive, so the treatment groups differ only on the treatment variable and not on other related characteristics.

##### Sub-par example

**Tip**: Try not avoid the following connection to the readings. What you see below is that the quote focuses exclusively on Utts. The sentences are not necessarily "wrong", but the framing puts the highlight away from your own voice. Use the assignment to showcase *your* analysis. You've done the work, read the books, and listened in class. Now give your analysis all of the ideas put together. **Make sure that you can back-up your analysis with something.** Use ideas and examples to support *your* analysis or to highlight the limitations of your analysis. That is, the assignment is to give your perspective using the readings to back you up. Stay away from the opposite: giving the readings as the assignment with your voice to back-up the readings.

> "In experimentation, we are concerned that each of the experimental units (people, animals, and so on) has a specified probability of receiving any of the potential treatments." (Utts 1999, p. 75). This quote shows that probability is used to decide which treatment is given to which person. That is important because then the treatment groups are balanced.

### Section Three: Reactions {.unnumbered}

In Section Three, you should write about your emotional reaction (how you felt) after class. Try to describe *in as much detail as possible* how class made you feel. For example, don't just say that class made you feel sad. Tell the reader what made you feel sad, how long you were sad, what does sadness feel like, did others notice, when did it stop, etc. It may be difficult for some of us to explore our feelings. Writing can be a useful way to examine feelings that we might otherwise ignore.

**Final tip**: Value the time you spend on each assignment. Your time and my time are both too valuable to waste.

## Special Project

For the last three regular class sessions (Nov 14, Nov 21, and Nov 28), you will be working together with your team on your special project. The topic of the project and its final product is flexible and should be decided together by your group.

Some guidelines:

1.  The topic should be related to statistics and real world applications. You may choose a topic that we have already discussed, or you may instead focus on a topic that we have not discussed (e.g., from your text).

2.  The project must be grounded in scientific evidence and be supported by documentation and citations. The project should reflect rigorous scholarship (including citations / references section).

3.  Your group will produce a final product. There should be something permanent that is written, drawn, created, or built that can be submitted.

4.  The final product should be orientated towards action. Some examples include a letter to an elected official, a white paper for the warden, an education campaign poster.

5.  The product will be due at the start of class on Dec 10th.

6.During the class session on Dec 5th, your group will have 5-10 minutes to give a brief presentation describing your product to our class and the invited guests that will be followed by a 2 min Q&A.

7.  All team members should participate fully in selecting the topic, designing the product, implementing the project, and making the presentation on Dec 5th.

## Draft / Final Paper

#### Due Dates

-   The draft is due October 17, 2022. We will not have regular class. I will be at CRC during our Tuesday meeting time for one-on-one check-ins with each of the inside students. The outside students will sign up for check-ins during that week (in Claremont).\
-   Final paper is due December 12, 2022

#### Draft

The draft consists of *only* the content part of the final paper. You will choose **two** topics (two of the four that eventually end up in the final paper) and write about what you have come to know about them. You must have references or quotes to support your ideas. You should plan to write at least 2 typed pages on each topic (slightly longer if not typed).

#### Format

The final paper will have two dimensions to it: process and content. Your task is to consider the entire experience shared by the class over the past semester and write, in detail, about several aspects of our experience. In your paper, you need to explain and analyze what you learned over the course of the semester.

#### Section One: Process

In the first part of the paper, focus on the following issues:

-   The group dynamics and how/whether these dynamics seemed to change over the course of the semester -- and why.
-   Your own individual process, including your participation in the class, as well as your reflections on and feelings about the whole experience -- note any shifts that may have taken place in how you look at things; be sure to explain the effect that the experience has had on you.
-   Perceptions of others and how these perceptions might have changed (for example, your perceptions about other individuals, as well as their perceptions of you).

#### Section Two: Content

We explored the following **topics** during some of our sessions together:

::: columns
::: {.column width="50%"}
-   samples / sampling
-   experiments and observational studies
-   measuring
-   plotting and visualizations
-   causation
-   hypothesis testing
:::

::: {.column width="50%"}
-   statistical significance
-   probability\* confidence intervals
-   ethical dilemmas in statistics
-   chapter in the book that you read on your own
-   new topic from your special project
:::
:::

Please take at least **four** of these topics and, supported by the assigned readings, explain **in depth** what you have come to understand about each one. Focus especially on new dimensions of the topic that you have come to realize through the course discussions and/or the readings. Clearly delineate the four separate topics with subheadings within the Content section of the paper.

#### Specifications of the Paper

You may type or hand-write the paper. If your paper is typed, it should be 10 pages in length, double-spaced, with one-inch margins. Double-sided printing is preferred (5 pages with typing on both sides), but single-sided printing is also acceptable (10 pages with typing on one side). If your paper is hand-written, it should be 15 pages with writing only on one side of the page, and please skip lines.

You must incorporate at least 15 references, quotes, or ideas (with citations) from the readings in the content portion of the paper (Section Two). Generally, in science, citations do not include page numbers (and often the citation comes from a paraphrase instead of a direct quotation). Typically the citation is given in text as "Author (year)" with a full citation given at the end of the paper (see how your textbook provides citations). However, you will not be graded on a particular format of the citations; you will be graded on **whether or not you have given credit** to any ideas or quotations you provide that are not your own.

Please take your time planning and writing your paper so that the result has the depth that it deserves. Provide a short introduction and conclusion.

#### In summary...

The final paper needs to have 4 parts:

1.  Short Introduction
2.  Section One -- Process
3.  Section Two -- Content
4.  Short Conclusion
